In [2]:
import tensorflow as tf
x=tf.constant([2.3,5.4,0.9,0.8],shape=[1,4],name='x')
y=tf.constant([0.3,0.4,2.9,3.8],shape=[1,4],name='y')
with tf.name_scope("mean"):
    with tf.name_scope("mean_of_x_y"):
        x1=tf.reduce_mean(x)
        y1=tf.reduce_mean(y)
        sess=tf.Session()
    print(sess.run(x1))
    print(sess.run(y1))
with tf.name_scope("variance"):
    with tf.name_scope("scope_SUB1"):
        a=tf.subtract(x,x1)
        sess1=tf.Session()
    print(sess1.run(a))
    with tf.name_scope("scope_SUB2"):
        b=tf.subtract(y,y1)
        sess2=tf.Session()
    print(sess2.run(b))
    with tf.name_scope("scope_sqr"):
        a1=tf.multiply(a,a)
        sess3=tf.Session()
    print(sess3.run(a1))
    with tf.name_scope("scope_of_Summation"):
        var=tf.reduce_sum(a1)
        sess4=tf.Session()
    print(sess4.run(var))
with tf.name_scope("covariance"):
    with tf.name_scope("Multiplication"):
        mul1=tf.multiply(a,b)
        sess5=tf.Session()
    print(sess5.run(mul1))
    with tf.name_scope("scope_of_Summation2"):
        mul2=tf.reduce_sum(mul1)
        sess6=tf.Session()
    print(sess6.run(mul2))
with tf.name_scope("value_of_c"):
    with tf.name_scope("Division"):
        c=tf.divide(mul2,var)
        sess7=tf.Session()
        print(sess7.run(c))
with tf.name_scope("value_of_m"):
    with tf.name_scope("Multiplication2"):
            c1=tf.multiply(c,x1)
            sess8=tf.Session()
            print(sess8.run(c1))
    with tf.name_scope("scope_SUB3"):
            c2=tf.subtract(y1,c1)
            sess9=tf.Session()
            print(sess9.run(c2))    
            writer = tf.summary.FileWriter("/tmp/tboard/lab2", sess.graph)
            writer.close()

2.35
1.85
[[-0.04999995  3.05000019 -1.44999993 -1.54999995]]
[[-1.54999995 -1.44999993  1.05000019  1.95000005]]
[[  2.49999529e-03   9.30250072e+00   2.10249972e+00   2.40249991e+00]]
13.81
[[ 0.07749993 -4.42250013 -1.52250016 -3.02250004]]
-8.89
-0.643736
-1.51278
3.36278
